apiVersion: apps/v1
kind: Deployment
metadata:
  name: test0512-003
  labels:
    app: test0512-003
  namespace: namespace-workflow-1683905029548
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test0512-003
  template:
    metadata:
      labels:
        app: test0512-003
    spec:
      containers:
        - name: test0512-003
          image: registryadminon.azurecr.io/image-workflow-1683905029548:latest
          ports:
            - containerPort: 8000