apiVersion: apps/v1
kind: Deployment
metadata:
  name: test0612-001
  labels:
    app: test0612-001
  namespace: namespace-workflow-1686597968789
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test0612-001
  template:
    metadata:
      labels:
        app: test0612-001
    spec:
      containers:
        - name: test0612-001
          image: wyregistry.azurecr.io/image-workflow-1686597968789:latest
          ports:
            - containerPort: 8000