apiVersion: apps/v1
kind: Deployment
metadata:
  name: test0417-005
  labels:
    app: test0417-005
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test0417-005
  template:
    metadata:
      labels:
        app: test0417-005
    spec:
      containers:
        - name: test0417-005
          image: acrworkflow1681747396022.azurecr.io/image-workflow-1681747396022:latest
          ports:
            - containerPort: 80