apiVersion: apps/v1
kind: Deployment
metadata:
  name: test0412
  labels:
    app: test0412
  namespace: namespace-workflow-1681331771905
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test0412
  template:
    metadata:
      labels:
        app: test0412
    spec:
      containers:
        - name: test0412
          image: acrworkflow1681331771905.azurecr.io/image-workflow-1681331771905:latest
          ports:
            - containerPort: 80