apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbug1
  labels:
    app: testbug1
  namespace: namespace-workflow-1684376036106
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbug1
  template:
    metadata:
      labels:
        app: testbug1
    spec:
      containers:
        - name: testbug1
          image: wytestacr001.azurecr.io/image-workflow-1684376036106:latest
          ports:
            - containerPort: 8000