apiVersion: apps/v1
kind: Deployment
metadata:
  name: test0417-002
  labels:
    app: test0417-002
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test0417-002
  template:
    metadata:
      labels:
        app: test0417-002
    spec:
      containers:
        - name: test0417-002
          image: acrworkflow1681745537531.azurecr.io/image-workflow-1681745537531:latest
          ports:
            - containerPort: 80