apiVersion: apps/v1
kind: Deployment
metadata:
  name: test0504
  labels:
    app: test0504
  namespace: namespace-workflow-1683218102497
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test0504
  template:
    metadata:
      labels:
        app: test0504
    spec:
      containers:
        - name: test0504
          image: acrworkflow1683218102497.azurecr.io/image-workflow-1683218102497:latest
          ports:
            - containerPort: 80