apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1234
  labels:
    app: test1234
  namespace: namespace-workflow-1683903691417
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1234
  template:
    metadata:
      labels:
        app: test1234
    spec:
      containers:
        - name: test1234
          image: wyregistrydemo.azurecr.io/testimage0512:latest
          ports:
            - containerPort: 8000