apiVersion: v1
kind: Service
metadata:
  name: testbug1
  namespace: namespace-workflow-1684376036106
spec:
  type: LoadBalancer
  selector:
    app: testbug1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000