apiVersion: v1
kind: Service
metadata:
  name: python-test
  namespace: namespace-workflow-1679342511452
spec:
  type: LoadBalancer
  selector:
    app: python-test
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000